### ISSUE TITLE
Test triplestores with VFB.owl using RDF4J front end

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/pipeline#26]
Aim: 
 - To benchmark speed.
 - Write SPARQL queries as input for prod & Elk server.

**Comment by dosumis** [comment]
Will probably materialise inside triplestore but this needs to be tested.

**Comment by matentzn** [comment]
- [x] Write pipeline that sets up a new rdf4j server, loads all datasets, and expose rf4j-workbench for query testing
- [x] Load VFB.owl into triple store
- [x] Run a few manual queries as a first basic test
- [ ] Write code for benchmarking query performance
- [ ] Write SPARQL query as input for NEO instance
- [ ] Write SPARQL query as input for ELK server

**Comment by matentzn** [comment]
Break the remaining todo items into new tickets.

**Comment by matentzn** [comment]
Ok, the pipeline to set up a new server, then populate a rdf4j in-memory triplestore is there. Will show the backend during the next dev. I think that this is okay for this sprint: The next steps are more involved and require more focused tickets.

**Comment by matentzn** [comment]
This epic is redundant with respect to other epics an tickets. Closing.
